package com.cehome.tiebaobei.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BRAND".
 */
public class Brand {

    private long id;
    private String name;
    private String enFirstChar;
    private Integer weight;
    private String hot;
    private String imageURL;

    public Brand() {
    }

    public Brand(long id) {
        this.id = id;
    }

    public Brand(long id, String name, String enFirstChar, Integer weight, String hot, String imageURL) {
        this.id = id;
        this.name = name;
        this.enFirstChar = enFirstChar;
        this.weight = weight;
        this.hot = hot;
        this.imageURL = imageURL;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEnFirstChar() {
        return enFirstChar;
    }

    public void setEnFirstChar(String enFirstChar) {
        this.enFirstChar = enFirstChar;
    }

    public Integer getWeight() {
        return weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    public String getHot() {
        return hot;
    }

    public void setHot(String hot) {
        this.hot = hot;
    }

    public String getImageURL() {
        return imageURL;
    }

    public void setImageURL(String imageURL) {
        this.imageURL = imageURL;
    }

}
