package com.cehome.tiebaobei.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CATEGORY_FILTER".
 */
public class CategoryFilter {

    private Integer filterId;
    private Integer categoryId;

    public CategoryFilter() {
    }

    public CategoryFilter(Integer filterId, Integer categoryId) {
        this.filterId = filterId;
        this.categoryId = categoryId;
    }

    public Integer getFilterId() {
        return filterId;
    }

    public void setFilterId(Integer filterId) {
        this.filterId = filterId;
    }

    public Integer getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

}
