package com.cehome.tiebaobei.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.cehome.tiebaobei.dao.ModelDao;
import com.cehome.tiebaobei.dao.BrandDao;
import com.cehome.tiebaobei.dao.CategoryDao;
import com.cehome.tiebaobei.dao.AreaDao;
import com.cehome.tiebaobei.dao.CategoryFilterDao;
import com.cehome.tiebaobei.dao.CategoryBrandModelDao;
import com.cehome.tiebaobei.dao.FilterDao;
import com.cehome.tiebaobei.dao.SortDao;
import com.cehome.tiebaobei.dao.VersionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 230): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 230;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        ModelDao.createTable(db, ifNotExists);
        BrandDao.createTable(db, ifNotExists);
        CategoryDao.createTable(db, ifNotExists);
        AreaDao.createTable(db, ifNotExists);
        CategoryFilterDao.createTable(db, ifNotExists);
        CategoryBrandModelDao.createTable(db, ifNotExists);
        FilterDao.createTable(db, ifNotExists);
        SortDao.createTable(db, ifNotExists);
        VersionDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        ModelDao.dropTable(db, ifExists);
        BrandDao.dropTable(db, ifExists);
        CategoryDao.dropTable(db, ifExists);
        AreaDao.dropTable(db, ifExists);
        CategoryFilterDao.dropTable(db, ifExists);
        CategoryBrandModelDao.dropTable(db, ifExists);
        FilterDao.dropTable(db, ifExists);
        SortDao.dropTable(db, ifExists);
        VersionDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(ModelDao.class);
        registerDaoClass(BrandDao.class);
        registerDaoClass(CategoryDao.class);
        registerDaoClass(AreaDao.class);
        registerDaoClass(CategoryFilterDao.class);
        registerDaoClass(CategoryBrandModelDao.class);
        registerDaoClass(FilterDao.class);
        registerDaoClass(SortDao.class);
        registerDaoClass(VersionDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
