package com.cehome.tiebaobei.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FILTER".
 */
public class Filter {

    private long id;
    private Integer parentId;
    private String name;
    private String multipleChoice;
    private Integer weight;

    public Filter() {
    }

    public Filter(long id) {
        this.id = id;
    }

    public Filter(long id, Integer parentId, String name, String multipleChoice, Integer weight) {
        this.id = id;
        this.parentId = parentId;
        this.name = name;
        this.multipleChoice = multipleChoice;
        this.weight = weight;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Integer getParentId() {
        return parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMultipleChoice() {
        return multipleChoice;
    }

    public void setMultipleChoice(String multipleChoice) {
        this.multipleChoice = multipleChoice;
    }

    public Integer getWeight() {
        return weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

}
